modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="uniquedungeons"
version="${file.jarVersion}"
displayName="Unique Dungeons"
logoFile="uniquedungeons.png"
description='''
Roleplay and Dungeon mod.
'''
[[dependencies.uniquedungeons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uniquedungeons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
